movies/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .views import LoginView, LogoutView, RegisterView
from . import settings


urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path("admin/", admin.site.urls),
    path("", include("movies_app.urls")),
    path("accounts/login/", LoginView.as_view(), name="login"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path("accounts/register/", RegisterView.as_view(), name="register"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("api-auth/", include("rest_framework.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies_app/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers, serializers, viewsets
from .models import Movie, Actor


# Serializers define the API representation.
class MovieSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Movie
        fields = [
            "movie_title",
            "movie_description",
            "pub_date",
            "time_create",
        ]


# ViewSets define the view behavior.
class MovieViewSet(viewsets.ModelViewSet):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r"movies-api", MovieViewSet)


app_name = "movies"
urlpatterns = [
    path("api/", include(router.urls)),
    path("", views.index, name="index"),
    path("movies/", views.MovieListView.as_view(), name="movies"),
    path("movies/<int:pk>/", views.MovieDetailView.as_view(), name="movie-detail"),
    path("actors/<int:actor_id>/", views.actor_detail, name="actor-detail"),
]

movies_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Actor(models.Model):
    name = models.CharField(max_length=100)
    photo = models.ImageField(upload_to="images/%Y/%m/%d/", blank=True)

    def __str__(self):
        return self.name


class Movie(models.Model):
    movie_title = models.CharField(max_length=200)
    movie_description = models.TextField()
    cast = models.ManyToManyField(Actor, blank=True)
    pub_date = models.DateTimeField("date published")
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=True)
    image = models.ImageField(upload_to="images/%Y/%m/%d/", blank=True)

    def __str__(self):
        return self.movie_title

class MovieComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    text = models.CharField(max_length=5000)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if len(self.text) > 100:
            return self.text[:100]
        else:
            return self.text

# class MovieActor(models.Model):
#     movie = models.ForeignKey(to=Movie, on_delete=models.DO_NOTHING)
#     actor = models.ForeignKey(to=Actor, on_delete=models.DO_NOTHING)

#     def __str__(self):
#         return (
#             Movie.objects.get(pk=self.movie.pk).__str__()
#             + Actor.objects.get(pk=self.actor.pk).__str__()
#         )

movies/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

movies_app/forms.py
from django import forms
from .models import MovieComment


class MovieCommentForm(forms.ModelForm): 
     class Meta:
          model = MovieComment
          fields = ["text"]

movies/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from .forms import RegisterForm


class LoginView(LoginView):
    next_page = reverse_lazy("movies:index")

class LogoutView(LogoutView):
    next_page = reverse_lazy("movies:index")

class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')

movies_app/views.py
from typing import Any, Dict
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.http import HttpResponse, Http404
from django.template import loader
from django.urls import reverse_lazy
from django.views import generic
from django.core.paginator import Paginator
from django.contrib.auth.views import LoginView
from math import ceil
from .models import Movie, Actor
from .forms import *


class MovieListView(generic.ListView):
    model = Movie
    template_name = "movies_app/index.html"
    paginate_by = 3

    def get_queryset(self):
        return Movie.objects.order_by("-pub_date")[:5]


class MovieDetailView(generic.DetailView, generic.CreateView):
    model = Movie
    template_name = "movies_app/movie_detail.html"
    form_class = MovieCommentForm
    success_url = reverse_lazy('movies:movie-detail')



def actor_detail(request, actor_id):
    actor = get_object_or_404(Actor, pk=actor_id)
    context = {"actor": actor}
    template = "movies_app/actor_detail.html"
    return render(request, template, context)


def index(request):
    return redirect("movies:movies")


# def register(request):
#     return HttpResponse("register")


# def login(request):
#     if request.POST:
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             print(form.cleaned_data)
#     else:
#         form = LoginForm()
#     return render(request, "movies_app/login.html", {"form": form})


# def index(request):
#     movie_list = Movie.objects.order_by("-pub_date")[:5]
#     context = {
#         "movie_list": movie_list,
#     }
#     return render(request, "movies_app/index.html", context)
#
#
# def detail(request, movie_id):
#     movie = get_object_or_404(Movie, pk=movie_id)
#     return render(request, "movies_app/detail.html", {"movie": movie})

movies_app/templates/movies_app/actor_detail.html
{% extends 'movies_app/base.html' %}

{% block title %}
{{ movie.movie_title }}
{% endblock title %}

{% block content %}
<h1>{{ actor.name }}</h1>

{% if actor.photo %}
<img src="{{ actor.photo.url }}" class="w-80"/>
{% endif %}
{% endblock content %}

movies_app/templates/movies_app/base.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="en" style="font-size: 14px;">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% endcompress css %}
    <link rel="icon" href="{% static 'movies_app/images/logo.png' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&display=swap" rel="stylesheet">
    <title>{% block title %}{% endblock title %}</title>
    {% block style %}
    {% endblock style %}
</head>

<body class="font-default bg-slate-100">
    <!-- Header -->
    {% include 'movies_app/header.html' %}
    <main class="w-full mt-5 md:mt-20">
        <!-- Блок контента -->
        {% block content %}
        {% endblock content %}
        <!-- Конец блока контента -->
    </main>
    <script src="{% static 'movies_app/scripts/script.js' %}"></script>
</body>

</html>

movies_app/templates/movies_app/header.html
{% load static %}

<!-- Блок главного меню -->
<header class="w-full bg-white/90 backdrop-blur-xl border-b radius-sm md:fixed md:top-0 md:left-0 md:right-0">
    <nav class="w-full sm:flex sm:justify-between">
        <ul class="flex ml-2 justify-between sm:justify-normal sm:gap-3 lg:ml-12 xl:ml-24">
            <li class="flex px-5 flex-col items-center justify-center">
                <a href="{% url 'movies:index' %}">
                    <img src="{% static 'movies_app/images/logo.png' %}" class="w-8" alt="logo"/>
                </a>
            </li>
            <li><a href="{% url 'movies:index' %}"
                    class="hidden sm:block text-slate-700 py-5 px-2 border-b-2 border-transparent hover:text-black hover:border-b-2 hover:border-indigo-500">
                    Home
                </a>
            </li>
            <li><a href="{% url 'movies:index' %}"
                    class="hidden sm:block text-slate-700 py-5 px-2 border-b-2 border-transparent hover:text-black hover:border-b-2 hover:border-indigo-500">
                    Movies
                </a>
            </li>
            <li><a href="{% url 'movies:index' %}"
                    class="hidden sm:block text-slate-700 py-5 px-2 border-b-2 border-transparent hover:text-black hover:border-b-2 hover:border-indigo-500">
                    Actors
                </a>
            </li>
            <li><a href="{% url 'movies:index' %}" id="menu-btn"
                    class="block mr-5 sm:hidden text-slate-700 py-5 px-2 border-b-2 border-transparent hover:text-black hover:border-b-2 hover:border-indigo-500">
                    Меню
                </a>
            </li>
        </ul>
        <div class="mr-7 flex items-center">
            {% if user.is_authenticated %}
            <p class="hidden sm:block">Welcome,&nbsp;</p> 
            <a href="#" class="hidden sm:block text-blue-500 hover:text-black hover:underline">
                {{ user.get_username }}
            </a>
            <div class="ml-5" class="hidden sm:block">
                <form action="{% url 'logout' %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Logout" class="hidden sm:block text-red-500 hover:underline hover:cursor-pointer">
                </form>
            </div>
            {% else %}
            <a href="{% url 'login' %}" class="hidden mr-5 sm:block text-slate-700 py-5 px-2 border-b-2 border-transparent hover:text-black hover:border-b-2 hover:border-indigo-500">
                Войти
            </a>
            <a href="{% url 'register' %}" class="hidden mr-5 sm:block text-slate-700 py-5 px-2 border-b-2 border-transparent hover:text-black hover:border-b-2 hover:border-indigo-500">
                Регистрация
            </a>
            {% endif %}
        </div>
        <div id="mobile-menu" class="hidden sm:hidden">mobile menu</div>
    </nav>
</header>
<!-- Конец блока главного меню -->

movies_app/templates/movies_app/index.html
{% extends 'movies_app/base.html' %}

{% block title %}
Главная | Фильмы
{% endblock title %}

{% block content %}
<ul class="mx-5 flex flex-col text-base lg:w-4/6 sm:mx-24 md:mx-24 lg:mx-32 xl:mx-44 2xl:max-w-screen-2xl">
    {% for movie in page_obj %}
    <li class="mb-5">
        <div class="p-4 shadow rounded-sm bg-white flex flex-col justify-left gap-5">
            <div>
                <a href="{% url 'movies:movie-detail' movie.id %}"
                    class="block mb-1 text-lg text-blue-600 hover:text-blue-700">
                    {{ movie.movie_title }}
                </a>
                <hr>
            </div>
            <div class="flex flex-col gap-5 md:flex-row">
                <div class="flex justify-center md:w-1/3 2xl:w-auto">
                    {% if movie.image %}
                    <a href="{% url 'movies:movie-detail' movie.id %}">
                        <img src="{{ movie.image.url }}" alt="<{{ movie.movie_title }}.jpg>"
                            class="w-80 xl:w-72 2xl:max-w-none" />
                    </a>
                    {% else %}
                    <i>Poster is missing...</i>
                    {% endif %}
                </div>
                <div class="md:w-2/3 2xl:w-auto">
                    {% if movie.cast.all %}
                    <p>
                        <b>Cast:</b>
                            {% for actor in movie.cast.all|slice:'3' %}
                            <a href="{% url 'movies:actor-detail' actor.pk %}"
                                class="text-blue-600 hover:text-blue-700 hover:underline">{{ actor.name }}</a>{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        
                    </p>
                    <br>
                    {% endif %}
                    <p class="font-base">
                        {{ movie.movie_description|truncatewords:50 }}
                        <a href="{% url 'movies:movie-detail' movie.id %}"
                            class="text-blue-600 hover:text-blue-700 hover:underline"><i>Read more</i></a>
                    </p>
                </div>
            </div>
        </div>
    </li>
    {% endfor %}
    {% include 'movies_app/paginator.html' %}
</ul>
{% endblock content %}

movies_app/templates/movies_app/movie_detail.html
{% extends 'movies_app/base.html' %}

{% block title %}
{{ movie.movie_title }}
{% endblock title %}

{% block style%}
<style type="text/css">
    .form-style-1 label{
        margin:0 0 3px 0;
    }
    .form-style-1 input[type=text], 
    .form-style-1 input[type=date],
    .form-style-1 input[type=datetime],
    .form-style-1 input[type=number],
    .form-style-1 input[type=search],
    .form-style-1 input[type=time],
    .form-style-1 input[type=url],
    .form-style-1 input[type=email],
    .form-style-1 input[type=password],
    textarea, 
    select{
        box-sizing: border-box;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        border:1px solid #BEBEBE;
        padding: 7px;
        margin:0px;
        -webkit-transition: all 0.30s ease-in-out;
        -moz-transition: all 0.30s ease-in-out;
        -ms-transition: all 0.30s ease-in-out;
        -o-transition: all 0.30s ease-in-out;
        outline: none;	
    }
    .form-style-1 input[type=text]:focus, 
    .form-style-1 input[type=date]:focus,
    .form-style-1 input[type=datetime]:focus,
    .form-style-1 input[type=number]:focus,
    .form-style-1 input[type=search]:focus,
    .form-style-1 input[type=time]:focus,
    .form-style-1 input[type=url]:focus,
    .form-style-1 input[type=email]:focus,
    .form-style-1 input[type=password]:focus,
    .form-style-1 textarea:focus, 
    .form-style-1 select:focus{
        -moz-box-shadow: 0 0 8px #88D5E9;
        -webkit-box-shadow: 0 0 8px #88D5E9;
        box-shadow: 0 0 8px #88D5E9;
        border: 1px solid #88D5E9;
    }
    .form-style-1 input[type=submit], .form-style-1 input[type=button]{
        background: #4B99AD;
        padding: 8px 15px 8px 15px;
        border: none;
        color: #fff;
    }
    .form-style-1 input[type=submit]:hover, .form-style-1 input[type=button]:hover{
        background: #4691A4;
        box-shadow:none;
        -moz-box-shadow:none;
        -webkit-box-shadow:none;
    }
</style>
{% endblock style%}

{% block content %}
<h1>{{ movie.movie_title }}</h1>

<p>
    Cast: <i>{{ movie.cast.all|join:", "|default:"somebody" }}.</i>
</p>

<p>{{ movie.movie_description|linebreaks }}</p>
<div class="flex flex-col gap-3 bg-white px-10 pb-10 pt-8 w-84 max-w-lg sm:w-2/3">
<form action="{% url 'movies:movie-detail' movie.pk %}" method="POST" class="flex flex-col gap-5 form-style-1">
    {% csrf_token %}
    {% for f in form %}
    <div class="flex flex-col">
        <label for="{{ f.id_for_label }}" class="font-bold">{{ f.label }}</label>
        {{ f }}
        <div class="text-red-500">{{ f.errors }}</div>
    </div>
    {% endfor %}
    <input type="submit" value="Send">
</form>
</div>
{% endblock content %}

movies_app/templates/movies_app/paginator.html
<nav class="mb-16 pl-4 flex">
    <ul class="flex">
        <li>
            <a href="{% url 'movies:movies'%}?page=1" 
            class="relative block rounded bg-transparent px-3 py-1.5 text-sm text-neutral-600 transition-all duration-300 {% if i != current_page %}hover:bg-slate-200{% endif %}  dark:text-white dark:hover:bg-neutral-700 dark:hover:text-white">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% if page_obj.has_previous %}
        <li>
            <a href="{% url 'movies:movies'%}?page={{page_obj.previous_page_number}}" 
            class="relative block rounded bg-transparent px-3 py-1.5 text-sm text-neutral-600 transition-all duration-300 hover:bg-slate-200  dark:text-white dark:hover:bg-neutral-700 dark:hover:text-white">{{ page_obj.previous_page_number }}</a>
        </li>
        {% endif %}
        <li>
            <a href="#"
            class="relative block rounded bg-gray-300 px-3 py-1.5 text-sm text-neutral-600 transition-all duration-300 hover:bg-slate-200 dark:text-white dark:hover:bg-neutral-700 dark:hover:text-white">{{ page_obj.number }}</a>
        </li>
        {% if page_obj.has_next %}
        <li>
            <a href="{% url 'movies:movies'%}?page={{page_obj.next_page_number}}" 
            class="relative block rounded bg-transparent px-3 py-1.5 text-sm text-neutral-600 transition-all duration-300 hover:bg-slate-200  dark:text-white dark:hover:bg-neutral-700 dark:hover:text-white">{{ page_obj.next_page_number }}</a>
        </li>
        {% endif %}
        <li>
            <a href="{% url 'movies:movies'%}?page={{ page_obj.paginator.num_pages }}" 
            class="relative block rounded bg-transparent px-3 py-1.5 text-sm text-neutral-600 transition-all duration-300 hover:bg-slate-200  dark:text-white dark:hover:bg-neutral-700 dark:hover:text-white">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>

templates/movies_app/actor.html
{% extends 'movies_app/base.html' %}

{% block title %}
{{ movie.movie_title }}
{% endblock title %}

{% block content %}
<h1>{{ actor.name }}</h1>

{% if actor.photo %}
<img src="{{ actor.photo.url }}" class="w-80"/>
{% endif %}
{% endblock content %}

templates/movies_app/detail.html
{% extends 'movies_app/base.html' %}

{% block title %}
{{ movie.movie_title }}
{% endblock title %}

{% block content %}
<h1>{{ movie.movie_title }}</h1>

<p>
    Cast: <i>{{ movie.cast.all|join:", "|default:"somebody" }}.</i>
</p>

<p>{{ movie.movie_description|linebreaks }}</p>
{% endblock content %}